### ISSUE TITLE
Image posts are viewed wrongly on firefox.

### ISSUE THREAD

**Issue by maddovr** [Ganevru/gatsby-starter-blog-grommet#1]
Hello, nice starter for gatsby, however I noticed that your posts containing images renders weirdly: [](https://abload.de/img/screenshot-2018-10-103zf5p.png)
Everything works as intended in chrome.

**Comment by maddovr** [comment]
Screenshot didn't work, but here it is https://abload.de/img/screenshot-2018-10-103zf5p.png

**Comment by ganevdev** [comment]
Hi thanks. Just fixed it.
