### ISSUE TITLE
Layer - failure to build

### ISSUE THREAD

**Issue by ench0** [Ganevru/gatsby-starter-blog-grommet#4]
First, thanks for the starter, I have switched my website completely to this and learned few things along the way. Is it only me, or there is an issue with Gatsby + Grommet when adding Layer component? It will work great on dev, but when building for production it will produce an error.

### How to reproduce?
Add <Layer /> (with or without children/props) anywhere in the code, ie:

    <Grommet theme={THEMES[themeByThemeType(themeType)]}>

      <Grommet theme={siteTheme}>

        <Layer />

        <GlobalStyle />

        <Box direction="column" align="center">

        ...

The build will fail with

    error Building static HTML failed for path "/blog/as-you/"

    See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

    24 |     _this = _Component.call.apply(_Component, [this].concat(args)) || this;

    25 | 

    > 26 |     _defineProperty(_assertThisInitialized(_assertThisInitialized(_this)), "originalFocusedElement", document.activeElement);

     | ^

    27 | 

    28 |     _defineProperty(_assertThisInitialized(_assertThisInitialized(_this)), "layerContainer", getNewContainer());
    29 | 

    WebpackError: ReferenceError: document is not defined

    - Layer.js:26 new Layer
    [lib]/[grommet]/es6/components/Layer/Layer.js:26:1

    - bootstrap:22 c
    lib/webpack/bootstrap:22:1

    - bootstrap:25 Sa
    lib/webpack/bootstrap:25:1

    - bootstrap:30 a.render
    lib/webpack/bootstrap:30:1

    - bootstrap:30 a.read
    lib/webpack/bootstrap:30:1

    - bootstrap:42 renderToString
    lib/webpack/bootstrap:42:1

    - static-entry.js:194 Module.default
    lib/.cache/static-entry.js:194:18

    - bootstrap:24 Promise
    lib/webpack/bootstrap:24:1

    - gatsby-browser-entry.js:11 Promise._resolveFromExecutor
    lib/.cache/gatsby-browser-entry.js:11:1

    - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1

    - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

    - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1

    - api-runner-ssr.js:6 MappingPromiseArray.PromiseArray._iterate
    lib/.cache/api-runner-ssr.js:6:16

    - bootstrap:67 MappingPromiseArray.init
    lib/webpack/bootstrap:67:1

    error Command failed with exit code 1.

Probably issue in between Gatsby - Grommet - Webpack trio. Any suggestions welcome.

**Comment by ganevdev** [comment]
Thanks for the feedback. The error works as you described. At the moment I have no idea where it comes from.

I wrote in Gatsby: [https://github.com/gatsbyjs/gatsby/issues/12467](https://github.com/gatsbyjs/gatsby/issues/12467). Maybe someone from there will help.

**Comment by ench0** [comment]
Thanks! It seems to be Grommet issue based on the reply. Would you mind opening an issue over there?

**Comment by ganevdev** [comment]
I opened an issue [Layer component Error in Gatsby js #2906](https://github.com/grommet/grommet/issues/2906)

**Comment by ench0** [comment]
> 
> 
> I opened an issue [Layer component Error in Gatsby js #2906](https://github.com/grommet/grommet/issues/2906)

Great, they recognised it as a bug. Thanks for following up!

**Comment by ganevdev** [comment]
And so, we received the answer - the layer element simply cannot be inserted as such, it can only be called (by pressing a button, for example).

Now I understand why the layer generally worked in my other gatsby projects, and I didn’t pay attention to it - I always used it as an element that can be called, and never even tried to just paste it.

**Comment by ench0** [comment]
So what would be your suggestion? I tried inserting layer that's hidden by default but that did not work as well. Should it be in separate file or something?

EDIT: inserting only `<Layer position="hidden" />` also fails. I guess only option is to make Layer available in separate component that is not initialised unless button is clicked or something similar. Hope that will work.

**Comment by ganevdev** [comment]
@ench0 - [https://github.com/Ganevru/gatsby-starter-blog-grommet-with-layer](https://github.com/Ganevru/gatsby-starter-blog-grommet-with-layer) - look at this repo, it is exactly the same as this starter, but it has a `LayerTest` component (several types of layers with buttons to call them) that I call in `Layout` - and everything works.

**Comment by ench0** [comment]
Thanks for all the help, really appreciated. Will have a look at that other repo.
